@hostname=http://localhost:8000

### 
# @name newchat
POST {{hostname}}/chat
Content-Type: application/json

{
  "message": "what is the hometown of the kilian jornet"
}
###

@threadId={{newchat.response.body.$.threadId}}

###
POST {{hostname}}/chat/resume
Content-Type: application/json

{
  "threadId": "{{threadId}}",
  "type": "accept"
}
###

###
POST {{hostname}}/chat/resume
Content-Type: application/json

{
  "threadId": "{{threadId}}",
  "type": "feedback",
  "message": "The plan is too long, come up with a shorter plan"
}
###