@hostname=http://localhost:8000

### 
# @name newchat
POST {{hostname}}/stream/chat
Content-Type: application/json

{
  "message": "what is the hometown of kilian jornet?"
}
###

@threadId={{newchat.response.body.$.threadId}}

###
POST {{hostname}}/stream/chat/resume
Content-Type: application/json

{
  "threadId": "3AOf66g311Iy8lKeyS6xr",
  "type": "accept"
}
###

###
POST {{hostname}}/stream/chat/resume
Content-Type: application/json

{
  "threadId": "amNBqH3VNcLBYZyh1lhYy",
  "type": "feedback",
  "message": "The plan is too long, come up with a shorter plan"
}
###